name: build and push

on:
  push:
    tags:
      - '*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: variables
        id: vars
        run: |
          echo "::set-output name=prefix::${{ secrets.DOCKERHUB_USERNAME }}/mit-scheme:${GITHUB_REF##*/v}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push arm64 image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          build-args: ARCH=aarch64le
          push: true
          tags: ${{ steps.vars.outputs.prefix }}-arm64
      -
        name: Build and push amd64 image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          build-args: ARCH=x86-64
          push: true
          tags: ${{ steps.vars.outputs.prefix }}-amd64
      - 
        name: Create and push the manifest for multi-arch
        run: |
          base_name=${{ steps.vars.outputs.prefix }}
          docker manifest create $base_name ${base_name}-amd64 ${base_name}-arm64
          docker manifest push $base_name
